language: php

matrix:
  include:
    - php: 7.4
      env:
        - RUN_TEST_COMMAND=php bin/phing test:behat
        - SETUP_DB=1
      services:
        - postgresql
      addons:
        postgresql: "10"
        apt:
          packages:
            - postgresql-10
            - postgresql-client-10
    - php: 7.4
      env:
        - RUN_TEST_COMMAND=php bin/phing test:unit
    - php: 7.4
      env:
        - RUN_TEST_COMMAND=php bin/phing check:style
install:
  - composer install

cache:
  directories:
    - "$HOME/.composer/cache"

before_script:
  - |
    if [[ "$SETUP_DB" == 1 ]] ; then
      psql -c "CREATE ROLE ergonode LOGIN  PASSWORD '123' CREATEDB" -U postgres
      psql -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres --dbname template1
      psql -c 'CREATE EXTENSION IF NOT EXISTS "ltree";' -U postgres --dbname template1
      psql -c 'CREATE DATABASE ergonode_test OWNER ergonode' -U postgres
    fi


  - openssl genrsa -aes256 -passout pass:1234 -out "config/jwt/private.pem" 4096
  - openssl rsa -pubout -in "config/jwt/private.pem"  -passin pass:1234 -out "config/jwt/public.pem"
env:
  global:
    - APP_ENV=test
    - DATABASE_URL="pgsql://ergonode:123@localhost:5432/ergonode_test?serverVersion=10&charset=utf8"
script:
  - export DATABASE_URL="pgsql://ergonode:123@localhost:5432/ergonode_test?serverVersion=10&charset=utf8"
  - $RUN_TEST_COMMAND
